version: '2'
services:
  data:
    image: creemson/data
#    restart: always
    volumes:
      - ./Docker/Data/datadir:/var/lib/mysql
  mariadb:
    image: mariadb:latest
#    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 99zkAjKJdCtLwLRH
      MYSQL_DATABASE: fc5api
      MYSQL_USER: mysqlcreemson
      MYSQL_PASSWORD: PF7j3vZUpqdjarkM
    volumes_from:
        - data
  web:
    image: creemson/apache_php
    ports:
      - 60001:80
    environment:
      XDEBUG_CONFIG: remote_host=172.22.0.1
      volumes_from: application
      links: mariadb
    volumes:
      - ./application:/var/www/html
