easy_admin:
    site_name: 'FC5 API'
    design:
        brand_color: '#5db55b'
    entities:
#        Option:
#            class: AppBundle\Entity\Option
#            label: 'Options'
#            form:
#                fields:
#                    - { property : "logo", label : "Logo" }
#                    - { property : "address", label : "Address" }
#                    - { property : "email", label : "Email" }
#                    - { property : "officeAndPartners", label : "Office and partners" }
#                    - { property: 'backgroundContactFile', type: 'vich_image', base_path: '%app.path.background_image%' }
#                    - { property: 'backgroundContactSmallFile', type: 'vich_image', base_path: '%app.path.background_image%' }
#            disabled_actions: ["show", "delete", "new", "search"]
#        Section:
#            class: AppBundle\Entity\Section
#            label: 'Sections'
#            form:
#                fields:
#                    - { property : "title", label : "Title" }
#                    - { property : "subTitle", label : "Sub Title" }
#                    - { property : "content", label : "Description" }
#                    - { property : "quote", label : "Quote" }
#                    - { property : "authorQuote", label : "Quote author" }
#                    - { property : "cardTitle", label : "Card Title" }
#                    - { property : "cardContent", label : "card Content" }
#                    - { property : "showLogos", label : "show logos" }
#                    - { property : "showSocials", label : "show socials" }
#                    - { property: 'backgroundFile', type: 'vich_image', base_path: '%app.path.background_image%' }
#                    - { property: 'backgroundSmallFile', type: 'vich_image', base_path: '%app.path.background_image%' }
#            disabled_actions: ["show"]
#            list:
#                title: "List of sections"
#                actions:
#                    - { name : "edit", icon : "", label : "Edit" }
#                    - { name : "delete", icon : "", label : "Delete" }
#                    - { name : "new", label : "Add a section" }
#                fields:
#                    - { property : "title", label : "Titre" }
#                    - { property: 'background', type: 'image', base_path: '%app.path.background_image%' }
        BlazonShape:
            class: AppBundle\Entity\BlazonShape
            label: 'Blazon Shape'
            form:
                fields:
                    - { property : "svg", label : "Svg" }
                    - { property : "premium", label : "Premium" }
                    - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.image%' }
            disabled_actions: ["show"]
            list:
                title: "List of blazon shapes"
                actions:
                    - { name : "edit", icon : "", label : "Edit" }
                    - { name : "delete", icon : "", label : "Delete" }
                    - { name : "new", label : "Add a Blazon shape" }
                fields:
                    - { property : "alt", label : "Alt" }
                    - { property: 'image', type: 'image', base_path: '%app.path.image%' }
        Club:
            class: AppBundle\Entity\Club
        Page:
            class: AppBundle\Entity\Page
        Event:
            class: AppBundle\Entity\Event
        EventType:
            class: AppBundle\Entity\EventType
        Player:
            class: AppBundle\Entity\Player
        StoreItem:
            class: AppBundle\Entity\StoreItem
        Nationality:
            class: AppBundle\Entity\Nationality
        League:
            class: AppBundle\Entity\League
        User:
            class: AppBundle\Entity\User
            label: 'Users'
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
